### ISSUE TITLE
Wave vector output along ray

### ISSUE THREAD

**Issue by dylanmikesell** [LANL-Seismoacoustics/GeoAc#3]
Hi,

Is it possible to easily output the wave vector (k_phi, k_theta, k_r) at each point along the ray in the Global propagation models? I am interested in getting this from _GeoAcGlobal_RunProp_ and _GeoAcGlobal_RngDep_RunProp_.

I would like to add something like 
```
raypath << '\t' << k_r;
raypath << '\t' << k_p;
raypath << '\t' << k_t << '\n';
```
in the WriteRays call. I have not gone through the code completely, but hoping someone can point to where I should start.

**Comment by dylanmikesell** [comment]
Does anyone monitor this repository?

**Comment by philblom** [comment]
Additional ouput along the ray path can be added in Code/GeoAcGlobal_main.cpp lines 267 through 273 and Code/GeoAcGlobal.RngDep_main.cpp in lines 275 - 282 (raypaths file).  
Those outputs already include geometric location, travel time, spreading and absorption losses, etc.  

If you're just looking for the wavefront geometry, the eikonal vector components are included in the "solution" array (elements 0, 1, and 2 are already output):
solution[m][0] = r value
solution[m][1] = latitude value (in radians)
solution[m][2] = longitude value (in radians)
solution[m][3] = r component of eikonal vector
solution[m][4] = latitude component of eikonal vector
solution[m][5] = longitude component of eikonal vector

Hope that's enough to get the output you need.

**Comment by dylanmikesell** [comment]
Excellent! That is all I needed. Thank you very much for the hint.

Dylan
